/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ex01atm;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author yoyo.yao
 */
public class FastCash extends javax.swing.JFrame {

    /**
     * Creates new form FastCash
     */
    public FastCash() {
        initComponents();
    }
    
    int accNum;
    public FastCash(int AccountNumber) {
        initComponents();
        accNum = AccountNumber;
        lblAccountNumber.setText("Account Number: " + accNum);
        getBalance();
    }
    
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Statement st = null;
    int oldBalance;
    
    private void getBalance() {
        String query = "select * from account where AccountNumber='"+accNum+"'";
        try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","");        
                st = con.createStatement();
                rs = st.executeQuery(query);
                if (rs.next()) {
                    oldBalance = rs.getInt(11);
                    lblBalance.setText("Balance: " + oldBalance);
                } else {
                   
                }
            } catch(Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
    }
    
    // update transaction table
    private void updateTransactionTable(int toWithdraw) {
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","");      
            String query = "select id from transaction order by id desc limit 0, 1";
            st = con.createStatement();
            rs = st.executeQuery(query);
            int idToInsert = 0;
            if (rs.next()) {
                idToInsert = rs.getInt(1) + 1;
            } else {
                idToInsert = 1;
            }
            
            query = "insert into transaction values(?,?,?,?,?)";
            ps = con.prepareStatement(query);
            ps.setInt(1, idToInsert);
            ps.setInt(2, accNum);
            ps.setString(3, "Withdraw");
            ps.setInt(4, toWithdraw);
            java.util.Date udt = new java.util.Date();
            java.sql.Date sdt = new java.sql.Date(udt.getTime());
            ps.setDate(5, sdt);
            int row = ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Transaction saved");
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void fastWithdraw(int toWithdraw) {
        getBalance();
        if (toWithdraw > oldBalance) {
            JOptionPane.showMessageDialog(this, "Can't withdraw more than current balance");
            return;
        }
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atm","root","");
            String query = "update account set Balance=? where AccountNumber=?";
            ps = con.prepareStatement(query);
            ps.setInt(1, oldBalance - toWithdraw);
            ps.setInt(2, accNum);
            if (ps.executeUpdate() == 1) {
                JOptionPane.showMessageDialog(this, "Balance updated");
                getBalance();
                updateTransactionTable(toWithdraw);
            } else {
                JOptionPane.showMessageDialog(this, "Missing information");
            }
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(this, e);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCash100 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCash50 = new javax.swing.JButton();
        btnCash200 = new javax.swing.JButton();
        btnCash500 = new javax.swing.JButton();
        btnCash1000 = new javax.swing.JButton();
        btnCash2000 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblAccountNumber = new javax.swing.JLabel();
        lblBalance = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnCash100.setText("$100");
        btnCash100.setToolTipText("");
        btnCash100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash100MouseClicked(evt);
            }
        });
        btnCash100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash100ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATM");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fast Cash");

        btnCash50.setText("$50");
        btnCash50.setToolTipText("");
        btnCash50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash50MouseClicked(evt);
            }
        });
        btnCash50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash50ActionPerformed(evt);
            }
        });

        btnCash200.setText("$200");
        btnCash200.setToolTipText("");
        btnCash200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash200MouseClicked(evt);
            }
        });
        btnCash200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash200ActionPerformed(evt);
            }
        });

        btnCash500.setText("$500");
        btnCash500.setToolTipText("");
        btnCash500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash500MouseClicked(evt);
            }
        });
        btnCash500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash500ActionPerformed(evt);
            }
        });

        btnCash1000.setText("$1000");
        btnCash1000.setToolTipText("");
        btnCash1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash1000MouseClicked(evt);
            }
        });
        btnCash1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash1000ActionPerformed(evt);
            }
        });

        btnCash2000.setText("$2000");
        btnCash2000.setToolTipText("");
        btnCash2000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCash2000MouseClicked(evt);
            }
        });
        btnCash2000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCash2000ActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.setToolTipText("");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAccountNumber.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        lblAccountNumber.setText("Account Number: ");

        lblBalance.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 16)); // NOI18N
        lblBalance.setText("Balance: ");

        lblExit.setText("X");
        lblExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit.setPreferredSize(new java.awt.Dimension(20, 20));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCash50, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCash100, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCash200, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCash500, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnCash1000, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCash2000, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCash50, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCash100, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCash200, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCash500, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCash1000, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCash2000, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAccountNumber)
                .addGap(18, 18, 18)
                .addComponent(lblBalance)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCash100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash100ActionPerformed

    }//GEN-LAST:event_btnCash100ActionPerformed

    private void btnCash50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCash50ActionPerformed

    private void btnCash200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCash200ActionPerformed

    private void btnCash500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCash500ActionPerformed

    private void btnCash1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash1000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCash1000ActionPerformed

    private void btnCash2000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCash2000ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCash2000ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCash50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash50MouseClicked
        fastWithdraw(50);
    }//GEN-LAST:event_btnCash50MouseClicked

    private void btnCash100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash100MouseClicked
        fastWithdraw(100);
    }//GEN-LAST:event_btnCash100MouseClicked

    private void btnCash200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash200MouseClicked
        fastWithdraw(200);
    }//GEN-LAST:event_btnCash200MouseClicked

    private void btnCash500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash500MouseClicked
        fastWithdraw(500);
    }//GEN-LAST:event_btnCash500MouseClicked

    private void btnCash1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash1000MouseClicked
        fastWithdraw(1000);
    }//GEN-LAST:event_btnCash1000MouseClicked

    private void btnCash2000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCash2000MouseClicked
        fastWithdraw(2000);
    }//GEN-LAST:event_btnCash2000MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        new MainMenu(accNum).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(1);
    }//GEN-LAST:event_lblExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCash100;
    private javax.swing.JButton btnCash1000;
    private javax.swing.JButton btnCash200;
    private javax.swing.JButton btnCash2000;
    private javax.swing.JButton btnCash50;
    private javax.swing.JButton btnCash500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblExit;
    // End of variables declaration//GEN-END:variables
}
